### ISSUE TITLE
django-pipeline >= 1.6

### ISSUE THREAD

**Issue by ignatenkobrain** [niwinz/django-jinja#181]
I''m packaging django-ninja for Fedora and we have only 1.6.x package. Would be nice to get support for >=1.6.

I tried to do it myself, but I failed.

**Comment by jwhitlock** [comment]
Can you be more specific on your failures? The combination of django-pipeline 1.6.8 and django-jinja 2.2.1 appears to be working for me.  I'm also not sure if you meant "django-jinja" or "django-ninja"

**Comment by ignatenkobrain** [comment]
I see such traceback when running tests. Sorry for typo, sure it was django-jinja (was sleepy).
```python
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/django/views/generic/dates.py", line 343, in get
    return self.render_to_response(context)
  File "/usr/lib/python2.7/site-packages/django/views/generic/base.py", line 132, in render_to_response
    template=self.get_template_names(),
  File "../django_jinja/views/generic/base.py", line 26, in get_template_names
    ext = get_match_extension(using=getattr(self, 'template_engine', None))
  File "../django_jinja/base.py", line 98, in get_match_extension
    engine = Jinja2.get_default()
  File "/usr/lib/python2.7/site-packages/django/utils/lru_cache.py", line 124, in wrapper
    result = user_function(*args, **kwds)
  File "../django_jinja/backend.py", line 125, in get_default
    jinja_engines = [engine for engine in engines.all()
  File "/usr/lib/python2.7/site-packages/django/template/utils.py", line 110, in all
    return [self[alias] for alias in self]
  File "/usr/lib/python2.7/site-packages/django/template/utils.py", line 101, in __getitem__
    engine = engine_cls(params)
  File "../django_jinja/backend.py", line 208, in __init__
    self._initialize_thirdparty()
  File "../django_jinja/backend.py", line 234, in _initialize_thirdparty
    import_module(file_mod_path)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/python2.7/site-packages/pipeline/templatetags/pipeline.py", line 13, in <module>
    from ..collector import default_collector
  File "/usr/lib/python2.7/site-packages/pipeline/collector.py", line 11, in <module>
    from pipeline.finders import PipelineFinder
  File "/usr/lib/python2.7/site-packages/pipeline/finders.py", line 8, in <module>
    from pipeline.conf import settings
  File "/usr/lib/python2.7/site-packages/pipeline/conf.py", line 127, in <module>
    settings = PipelineSettings(_settings.PIPELINE)
  File "/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
    return getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'PIPELINE'
```

According to their documentation we should use `PIPELINE` option instead of `PIPELINE_*` (https://django-pipeline.readthedocs.io/en/latest/installation.html#upgrading-from-1-5). But it didn't work completely for me.

**Comment by ignatenkobrain** [comment]
```
python2-django-1.9.8-1.fc25.noarch
python2-django-pipeline-1.6.8-1.fc26.noarch
```

**Comment by jwhitlock** [comment]
The error makes it look like there is something wrong with your settings file. Can you post your ``PIPELINE`` setting?

**Comment by ignatenkobrain** [comment]
I use settings file from upstream source: https://github.com/niwinz/django-jinja/blob/b8073c2ae8f7c8350ab695c637b6a55e04998f69/testing/settings.py

**Comment by ignatenkobrain** [comment]
apparently there is no `PIPELINE` settings.

**Comment by jwhitlock** [comment]
Thanks, that does make sense, and the local copy of testing is missing the new ``PIPELINE`` setting. I just added this last week to [my project](https://github.com/mozilla/kuma/pull/3951/files#diff-61a61acfc5dfb7ad94a50fde2865584eR938), so let me see if I can open a quick PR.

**Comment by jwhitlock** [comment]
Nope, not a quick fix.  It's easy enough to add a compatible ``PIPELINE`` to settings:
```
# Pipeline >=  1.7
PIPELINE = {
    'PIPELINE_ENABLED': PIPELINE_ENABLE,
    'STYLESHEETS': PIPELINE_CSS,
    'JAVASCRIPT': PIPELINE_JS,
    'CSS_COMPRESSOR': PIPELINE_CSS_COMPRESSOR,
    'JS_COMPRESSOR': PIPELINE_JS_COMPRESSOR,
}
```

but ``django/contrib/_pipeline/templatetags`` needs a ``django-pipeline`` 1.7 compat layer:

```
======================================================================
ERROR: test_pipeline_js_safe (testapp.tests.DjangoPipelineTestTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/john/src/django-jinja/testing/testapp/tests.py", line 310, in test_pipeline_js_safe
    result = template.render({})
  File "../django_jinja/backend.py", line 106, in render
    return mark_safe(self.template.render(context))
  File "/Users/john/src/django-jinja/.tox/py27/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/john/src/django-jinja/.tox/py27/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 1, in top-level template code
  File "../django_jinja/utils.py", line 36, in _decorator
    return mark_safe(function(*args, **kwargs))
  File "../django_jinja/contrib/_pipeline/templatetags/_pipeline.py", line 58, in compressed_js
    package = settings.PIPELINE_JS.get(name, {})
  File "/Users/john/src/django-jinja/.tox/py27/lib/python2.7/site-packages/pipeline/conf.py", line 124, in __getattr__
    return self.__getitem__(name)
  File "/Users/john/src/django-jinja/.tox/py27/lib/python2.7/site-packages/pipeline/conf.py", line 104, in __getitem__
    value = self.settings[key]
KeyError: 'PIPELINE_JS'
```

**Comment by ignatenkobrain** [comment]
That's basically why I opened this report ;)

**Comment by ignatenkobrain** [comment]
I tried to adjust that `settings.PIPELINE_JS.get()` thing, but behavior is really strange, it is supposed to be accessible by `settings.PIPELINE['JAVASCRIPT']`, but it's not. pipeline somehow creates `settings.JAVASCRIPT`.

Thats why I said that I failed.

**Comment by niwinz** [comment]
I'll try to take care of this tomorrow ;)

**Comment by niwinz** [comment]
I'm no longer activelly use pipeline mudule, so this is not a priority for me. But if somebody want to upgrade it, I'm gladly accept the PR.

**Comment by wizpig64** [comment]
closing this as we've removed pipeline in 4112c74e55807c3ee2cddd7316e1bab1c14f980f
