### ISSUE TITLE
Django==1.11 makemessages incompatibility

### ISSUE THREAD

**Issue by karolyi** [niwinz/django-jinja#194]
Hey,

when using, Django 1.11 (just released), there's the following error when attempting to run `manage.py makemessages`:

```python
Traceback (most recent call last):
  File "backend/manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/project/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/project/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/project/venv/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/project/venv/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/project/venv/lib/python3.6/site-packages/django_jinja/management/commands/makemessages.py", line 43, in handle
    old_endblock_re = trans_real.endblock_re
AttributeError: module 'django.utils.translation.trans_real' has no attribute 'endblock_re'
```

Just letting you know.

Cheers

**Comment by karolyi** [comment]
also, #191 still applies.

**Comment by niwinz** [comment]
Pushed fix to master! Please, let me know if it works as expected.

**Comment by karolyi** [comment]
that was fast!

I'll be testing it tomorrow and will let you know, thx.

**Comment by karolyi** [comment]
nope, still getting the same error:
```python
Traceback (most recent call last):
  File "/project/backend/manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/project/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/project/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/project/venv/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/project/venv/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/project/venv/lib/python3.6/site-packages/django_jinja/management/commands/makemessages.py", line 47, in handle
    old_endblock_re = trans_real.endblock_re
AttributeError: module 'django.utils.translation.trans_real' has no attribute 'endblock_re'
```
