### ISSUE TITLE
ImportError: cannot import name 'BoundField' from 'django.forms.forms'  w/Django 3.1

### ISSUE THREAD

**Issue by bschollnick** [niwinz/django-jinja#260]
This appears to be simply a bad import.  I'm going to look at patching it, time permitting.

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/benjamin/venvs/quickbbs/lib/python3.7/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/Users/benjamin/venvs/quickbbs/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 110, in inner_run
    autoreload.raise_last_exception()
  File "/Users/benjamin/venvs/quickbbs/lib/python3.7/site-packages/django/utils/autoreload.py", line 76, in raise_last_exception
    raise _exception[1]
  File "/Users/benjamin/venvs/quickbbs/lib/python3.7/site-packages/django/core/management/__init__.py", line 357, in execute
    autoreload.check_errors(django.setup)()
  File "/Users/benjamin/venvs/quickbbs/lib/python3.7/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/Users/benjamin/venvs/quickbbs/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/benjamin/venvs/quickbbs/lib/python3.7/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/Users/benjamin/venvs/quickbbs/lib/python3.7/site-packages/django_jinja/apps.py", line 12, in ready
    base.patch_django_for_autoescape()
  File "/Users/benjamin/venvs/quickbbs/lib/python3.7/site-packages/django_jinja/base.py", line 50, in patch_django_for_autoescape
    from django.forms.forms import BoundField
ImportError: cannot import name 'BoundField' from 'django.forms.forms' (/Users/benjamin/venvs/quickbbs/lib/python3.7/site-packages/django/forms/forms.py)

```

**Comment by wizpig64** [comment]
I fixed this import in #259. there's no release yet that claims full django 3.1 support, but you could install master like this, and see if it has any more errors:

```
$ python -m pip install https://github.com/niwinz/django-jinja/archive/7d08e5d5d7cad5c00b65fd7c4b4f095f209a4162.tar.gz#egg=django_jinja
```

**Comment by bschollnick** [comment]
So far, so good.  Using:

$ python -m pip install https://github.com/niwinz/django-jinja/archive/7d08e5d5d7cad5c00b65fd7c4b4f095f209a4162.tar.gz#egg=django_jinja
And verified that it is now working…. Thanks.
	- Benjamin

**Comment by bschollnick** [comment]
Spoke too soon.

With Django v3.09, it works fine.  If I force an upgrade to Django v3.1 it fails with the BoundField form.

I don't see PIP regressing the version, so as far as I can tell, it's still the version I fetched..

`(quickbbs) nerv:quickbbs benjamin$  python -m pip install https://github.com/niwinz/django-jinja/archive/7d08e5d5d7cad5c065fd7c4b4f095f209a4162.tar.gz#egg=django_jinja
Requirement already satisfied: django_jinja from https://github.com/niwinz/django-jinja/archive/7d08e5d5d7cad5c00b65fd7c4b4f095f209a4162.tar.gz#egg=django_jinja in /Users/benjamin/venvs/quickbbs/lib/python3.7/site-packages (2.6.0)
Collecting django<3.1,>=1.11
  Using cached Django-3.0.9-py3-none-any.whl (7.5 MB)
Requirement already satisfied: jinja2>=2.10 in /Users/benjamin/venvs/quickbbs/lib/python3.7/site-packages (from django_jinja) (2.11.2)
Requirement already satisfied: pytz in /Users/benjamin/venvs/quickbbs/lib/python3.7/site-packages (from django<3.1,>=1.11->django_jinja) (2020.1)
Requirement already satisfied: asgiref~=3.2 in /Users/benjamin/venvs/quickbbs/lib/python3.7/site-packages (from django<3.1,>=1.11->django_jinja) (3.2.10)
Requirement already satisfied: sqlparse>=0.2.2 in /Users/benjamin/venvs/quickbbs/lib/python3.7/site-packages (from django<3.1,>=1.11->django_jinja) (0.3.1)
Requirement already satisfied: MarkupSafe>=0.23 in /Users/benjamin/venvs/quickbbs/lib/python3.7/site-packages (from jinja2>=2.10->django_jinja) (1.1.1)
Installing collected packages: django
  Attempting uninstall: django
    Found existing installation: Django 3.1
    Uninstalling Django-3.1:
      Successfully uninstalled Django-3.1
Successfully installed django-3.0.9
WARNING: You are using pip version 20.1.1; however, version 20.2.1 is available.
You should consider upgrading via the '/Users/benjamin/venvs/quickbbs/bin/python3 -m pip install --upgrade pip' command.
(quickbbs) nerv:quickbbs benjamin$ pip install --upgrade --no-deps django
Collecting django
  Using cached Django-3.1-py3-none-any.whl (7.8 MB)
Installing collected packages: django
  Attempting uninstall: django
    Found existing installation: Django 3.0.9
    Uninstalling Django-3.0.9:
      Successfully uninstalled Django-3.0.9
Successfully installed django-3.1
WARNING: You are using pip version 20.1.1; however, version 20.2.1 is available.
You should consider upgrading via the '/Users/benjamin/venvs/quickbbs/bin/python3.7 -m pip install --upgrade pip' command.
(quickbbs) nerv:quickbbs benjamin$ server4
Running on nerv.local
Debug is  True
Running on nerv.local
Debug is  True
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/benjamin/venvs/quickbbs/lib/python3.7/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/Users/benjamin/venvs/quickbbs/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 110, in inner_run
    autoreload.raise_last_exception()
  File "/Users/benjamin/venvs/quickbbs/lib/python3.7/site-packages/django/utils/autoreload.py", line 76, in raise_last_exception
    raise _exception[1]
  File "/Users/benjamin/venvs/quickbbs/lib/python3.7/site-packages/django/core/management/__init__.py", line 357, in execute
    autoreload.check_errors(django.setup)()
  File "/Users/benjamin/venvs/quickbbs/lib/python3.7/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/Users/benjamin/venvs/quickbbs/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/benjamin/venvs/quickbbs/lib/python3.7/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/Users/benjamin/venvs/quickbbs/lib/python3.7/site-packages/django_jinja/apps.py", line 12, in ready
    base.patch_django_for_autoescape()
  File "/Users/benjamin/venvs/quickbbs/lib/python3.7/site-packages/django_jinja/base.py", line 50, in patch_django_for_autoescape
    from django.forms.forms import BoundField
ImportError: cannot import name 'BoundField' from 'django.forms.forms' (/Users/benjamin/venvs/quickbbs/lib/python3.7/site-packages/django/forms/forms.py)
`

**Comment by enricobarzetti** [comment]
@bschollnick There's a chance that you did not actually install the latest because there was an issue where the setup.py required django < 3.1.  I recently made a PR that was merged that fixed this (https://github.com/niwinz/django-jinja/pull/262).  Could you try again with the latest commit?  https://github.com/niwinz/django-jinja/commit/d025ccdcfce7c68390b6c6e307de8d43df538cd1

**Comment by auvipy** [comment]
it should be fixed in master. can you check from the master?

**Comment by bschollnick** [comment]
Okay, I tried a few different ways to download via pip, and never succeeded.

Instead I uninstalled Django_Jinja via Pip, and just downloaded the Master tree, and dropped it inside my app.  So far, it's working fine...   I just verified, and Django v3.1 is shown in Pip, so it'd be great if we could get a release to patch the requirement & BoundField issue.

**Comment by tomhamiltonstubber** [comment]
Can we get a release? This is fixed on master right?

**Comment by bschollnick** [comment]
It seems to be working fine.  So I would assume a master fix would be available?

**Comment by NetUnit** [comment]
I had the same case. I suppose here is the answer: https://stackoverflow.com/questions/55019076/django-crispy-forms. Mine had been fixed after updating django-crispy-forms: pip install django-crispy-forms -U.
